services:
  mssqlserver:
    container_name: reviews_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1Secure*Password1
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1433:1433"

  reviewswebapplication:
    container_name: reviews_api
    image: ivanpovaliaev/reviews_api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7274;
    build:
      context: .
      dockerfile: ReviewsWebApplication/Dockerfile
    ports:
      - "7274:7274"
    depends_on:
      - mssqlserver   
    restart: unless-stopped 

volumes:
   mssql_data: