// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reviews.Domain;

#nullable disable

namespace Reviews.Domain.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20241130182905_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reviews.Domain.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Reviews.Domain.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Grade")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 10, 25, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(3170),
                            Grade = 0.5,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 9, 16, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(3213),
                            Grade = 2.2999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 11, 18, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(3270),
                            Grade = 2.0,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2024, 10, 29, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(3284),
                            Grade = 2.7799999999999998,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2024, 9, 18, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(3298),
                            Grade = 3.0,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2024, 9, 5, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(3316),
                            Grade = 3.29,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2024, 9, 5, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(3331),
                            Grade = 2.3300000000000001,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2024, 9, 11, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(3340),
                            Grade = 1.6699999999999999,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2024, 10, 17, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(3355),
                            Grade = 3.25,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2024, 10, 3, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(3369),
                            Grade = 1.3799999999999999,
                            ProductId = 10
                        });
                });

            modelBuilder.Entity("Reviews.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 8, 26, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(1864),
                            Grade = 1,
                            ProductId = 1,
                            RatingId = 1,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 9, 24, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(1889),
                            Grade = 0,
                            ProductId = 1,
                            RatingId = 1,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, se",
                            UserId = 7
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 9, 9, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(1898),
                            Grade = 0,
                            ProductId = 2,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisici",
                            UserId = 8
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2024, 10, 2, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(1907),
                            Grade = 2,
                            ProductId = 2,
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur a",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2024, 10, 18, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(1916),
                            Grade = 5,
                            ProductId = 2,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, conse",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2024, 11, 10, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(1931),
                            Grade = 1,
                            ProductId = 2,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = 7
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2024, 9, 11, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(1944),
                            Grade = 4,
                            ProductId = 2,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2024, 11, 27, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(1954),
                            Grade = 1,
                            ProductId = 2,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2024, 10, 17, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(1964),
                            Grade = 4,
                            ProductId = 2,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ",
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2024, 9, 27, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(1982),
                            Grade = 3,
                            ProductId = 2,
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur",
                            UserId = 5
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2024, 9, 14, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(1992),
                            Grade = 1,
                            ProductId = 2,
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectet",
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2024, 10, 8, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2001),
                            Grade = 2,
                            ProductId = 2,
                            RatingId = 2,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inc",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2024, 11, 2, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2011),
                            Grade = 0,
                            ProductId = 3,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetu",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2024, 10, 19, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2020),
                            Grade = 4,
                            ProductId = 3,
                            RatingId = 3,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2024, 11, 16, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2067),
                            Grade = 2,
                            ProductId = 4,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adip",
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2024, 9, 16, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2077),
                            Grade = 4,
                            ProductId = 4,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit a",
                            UserId = 9
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2024, 11, 7, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2086),
                            Grade = 0,
                            ProductId = 4,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur a",
                            UserId = 9
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2024, 10, 3, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2096),
                            Grade = 3,
                            ProductId = 4,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2024, 10, 3, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2105),
                            Grade = 2,
                            ProductId = 4,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tem",
                            UserId = 9
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2024, 11, 19, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2115),
                            Grade = 0,
                            ProductId = 4,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in",
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2024, 10, 20, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2125),
                            Grade = 5,
                            ProductId = 4,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in",
                            UserId = 4
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2024, 11, 8, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2134),
                            Grade = 5,
                            ProductId = 4,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2024, 9, 18, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2144),
                            Grade = 4,
                            ProductId = 4,
                            RatingId = 4,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididu",
                            UserId = 9
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2024, 9, 1, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2153),
                            Grade = 3,
                            ProductId = 5,
                            RatingId = 5,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
                            UserId = 8
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2024, 9, 20, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2333),
                            Grade = 4,
                            ProductId = 5,
                            RatingId = 5,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consec",
                            UserId = 7
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2024, 11, 12, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2371),
                            Grade = 3,
                            ProductId = 5,
                            RatingId = 5,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labo",
                            UserId = 4
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2024, 10, 26, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2385),
                            Grade = 1,
                            ProductId = 5,
                            RatingId = 5,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipi",
                            UserId = 4
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2024, 11, 24, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2394),
                            Grade = 2,
                            ProductId = 5,
                            RatingId = 5,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit,",
                            UserId = 6
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2024, 11, 19, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2403),
                            Grade = 3,
                            ProductId = 5,
                            RatingId = 5,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = 8
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2024, 11, 4, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2413),
                            Grade = 3,
                            ProductId = 5,
                            RatingId = 5,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inc",
                            UserId = 5
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2024, 10, 23, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2436),
                            Grade = 3,
                            ProductId = 5,
                            RatingId = 5,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labor",
                            UserId = 4
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2024, 11, 22, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2446),
                            Grade = 5,
                            ProductId = 5,
                            RatingId = 5,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, conse",
                            UserId = 1
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2024, 10, 15, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2461),
                            Grade = 2,
                            ProductId = 6,
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = 5
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2024, 9, 18, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2480),
                            Grade = 4,
                            ProductId = 6,
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incid",
                            UserId = 5
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2024, 9, 4, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2489),
                            Grade = 2,
                            ProductId = 6,
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisi",
                            UserId = 5
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2024, 9, 13, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2503),
                            Grade = 5,
                            ProductId = 6,
                            RatingId = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut",
                            UserId = 9
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2024, 10, 30, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2512),
                            Grade = 5,
                            ProductId = 6,
                            RatingId = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s",
                            UserId = 4
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2024, 9, 3, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2522),
                            Grade = 1,
                            ProductId = 6,
                            RatingId = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s",
                            UserId = 8
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2024, 8, 24, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2531),
                            Grade = 4,
                            ProductId = 6,
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi",
                            UserId = 4
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2024, 11, 2, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2541),
                            Grade = 1,
                            ProductId = 7,
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ei",
                            UserId = 2
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2024, 11, 17, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2555),
                            Grade = 4,
                            ProductId = 7,
                            RatingId = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur a",
                            UserId = 2
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2024, 10, 19, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2565),
                            Grade = 0,
                            ProductId = 7,
                            RatingId = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2024, 9, 2, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2574),
                            Grade = 3,
                            ProductId = 7,
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo",
                            UserId = 7
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2024, 10, 17, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2583),
                            Grade = 2,
                            ProductId = 7,
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consec",
                            UserId = 1
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2024, 8, 27, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2593),
                            Grade = 4,
                            ProductId = 7,
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2024, 10, 29, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2603),
                            Grade = 3,
                            ProductId = 8,
                            RatingId = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tem",
                            UserId = 8
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2024, 11, 28, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2612),
                            Grade = 0,
                            ProductId = 8,
                            RatingId = 8,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, con",
                            UserId = 9
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2024, 11, 29, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2621),
                            Grade = 2,
                            ProductId = 8,
                            RatingId = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labo",
                            UserId = 2
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2024, 11, 17, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2693),
                            Grade = 3,
                            ProductId = 9,
                            RatingId = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed ",
                            UserId = 8
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2024, 10, 4, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2707),
                            Grade = 5,
                            ProductId = 9,
                            RatingId = 9,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit",
                            UserId = 9
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2024, 11, 26, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2716),
                            Grade = 5,
                            ProductId = 9,
                            RatingId = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do e",
                            UserId = 5
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2024, 9, 23, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2725),
                            Grade = 0,
                            ProductId = 9,
                            RatingId = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, cons",
                            UserId = 3
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2024, 10, 28, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2735),
                            Grade = 2,
                            ProductId = 10,
                            RatingId = 10,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = 3
                        },
                        new
                        {
                            Id = 54,
                            CreationDate = new DateTime(2024, 11, 7, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2744),
                            Grade = 3,
                            ProductId = 10,
                            RatingId = 10,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 8
                        },
                        new
                        {
                            Id = 55,
                            CreationDate = new DateTime(2024, 10, 7, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2753),
                            Grade = 0,
                            ProductId = 10,
                            RatingId = 10,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = 9
                        },
                        new
                        {
                            Id = 56,
                            CreationDate = new DateTime(2024, 10, 13, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2763),
                            Grade = 3,
                            ProductId = 10,
                            RatingId = 10,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = 8
                        },
                        new
                        {
                            Id = 57,
                            CreationDate = new DateTime(2024, 10, 22, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2773),
                            Grade = 0,
                            ProductId = 10,
                            RatingId = 10,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = 6
                        },
                        new
                        {
                            Id = 58,
                            CreationDate = new DateTime(2024, 10, 31, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2783),
                            Grade = 2,
                            ProductId = 10,
                            RatingId = 10,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 9
                        },
                        new
                        {
                            Id = 59,
                            CreationDate = new DateTime(2024, 9, 15, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2797),
                            Grade = 1,
                            ProductId = 10,
                            RatingId = 10,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius",
                            UserId = 3
                        },
                        new
                        {
                            Id = 60,
                            CreationDate = new DateTime(2024, 11, 11, 18, 29, 4, 938, DateTimeKind.Utc).AddTicks(2806),
                            Grade = 0,
                            ProductId = 10,
                            RatingId = 10,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit ",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Reviews.Domain.Models.Review", b =>
                {
                    b.HasOne("Reviews.Domain.Models.Rating", "Rating")
                        .WithMany("Reviews")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Reviews.Domain.Models.Rating", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
