// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reviews.Domain;

#nullable disable

namespace Reviews.Domain.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20241207224526_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reviews.Domain.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Reviews.Domain.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Grade")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 10, 11, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9421),
                            Grade = 2.7799999999999998,
                            ProductId = new Guid("1a0b4e57-f3a5-4431-ba0b-44f22d4445ad")
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 9, 8, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9453),
                            Grade = 1.1699999999999999,
                            ProductId = new Guid("6e81fd57-86d1-48d4-a67b-77deb3ca49fa")
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 11, 29, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9492),
                            Grade = 2.5,
                            ProductId = new Guid("36fbfacc-2eeb-4d5c-b59c-9a537d6555ce")
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2024, 10, 30, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9506),
                            Grade = 1.5,
                            ProductId = new Guid("744c50db-51fa-4372-ae48-7af6a27a0f9f")
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2024, 10, 21, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9520),
                            Grade = 2.5,
                            ProductId = new Guid("2de79e70-3efb-46ed-ad60-1038b9062ae1")
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2024, 9, 7, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9534),
                            Grade = 3.3300000000000001,
                            ProductId = new Guid("0230702b-5ed8-49a6-8954-6f88c02fa56f")
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2024, 10, 10, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9543),
                            Grade = 3.4399999999999999,
                            ProductId = new Guid("4bdc4182-b784-4239-a0be-f177f21322e8")
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2024, 11, 29, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9558),
                            Grade = 1.8,
                            ProductId = new Guid("12cfda6b-c3f8-4ed8-9057-e62dbe5f7ee3")
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2024, 11, 16, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9572),
                            Grade = 2.1699999999999999,
                            ProductId = new Guid("87eb8f90-6825-4e40-809e-5a1b5b70abe4")
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2024, 10, 21, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9587),
                            Grade = 3.3300000000000001,
                            ProductId = new Guid("8517b8a9-3d54-4e5c-aba7-f955e241f399")
                        });
                });

            modelBuilder.Entity("Reviews.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 10, 22, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(7935),
                            Grade = 3,
                            ProductId = new Guid("1a0b4e57-f3a5-4431-ba0b-44f22d4445ad"),
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing ",
                            UserId = "2e5f75cb-9551-47ec-a800-12fd0198ad55"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 10, 11, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(7977),
                            Grade = 4,
                            ProductId = new Guid("3cbe38ca-46e7-4c1a-9c24-ec92922a4ef1"),
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipis",
                            UserId = "49fa8992-8e5b-406d-80be-5102c929760d"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 10, 7, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8001),
                            Grade = 2,
                            ProductId = new Guid("66df5b5b-3862-4b03-a0bb-ff1a26609c9e"),
                            RatingId = 1,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = "9bd71a24-2335-49cd-8605-29019e401039"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2024, 11, 8, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8030),
                            Grade = 5,
                            ProductId = new Guid("e3f38cac-1536-421b-91f8-af004f69619a"),
                            RatingId = 1,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do e",
                            UserId = "8e523598-e12b-4815-a5d5-a1fd8e1d1a18"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2024, 9, 1, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8054),
                            Grade = 2,
                            ProductId = new Guid("8ceecc51-142c-44f9-8f21-9658852a243a"),
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ",
                            UserId = "cf19620b-d47c-4dd6-9822-c9c0a64da7d6"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2024, 11, 10, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8077),
                            Grade = 0,
                            ProductId = new Guid("75d5be46-561e-45f1-a598-9e454cda700b"),
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing eli",
                            UserId = "1a72f978-1397-4ce3-8684-0cc1fbd9a19a"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2024, 10, 31, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8096),
                            Grade = 3,
                            ProductId = new Guid("693828f9-cfc0-4b93-b74b-c59ce0b1db55"),
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod t",
                            UserId = "086a8c5c-fa3e-447e-8af4-c083577935b7"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2024, 10, 17, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8115),
                            Grade = 4,
                            ProductId = new Guid("14ec0fa5-c728-4dde-9dd5-6b256df3c899"),
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inc",
                            UserId = "a26d02bf-1204-44f1-9ab6-d90aedb852ce"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2024, 9, 9, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8138),
                            Grade = 2,
                            ProductId = new Guid("3674333e-9316-4f9f-a46f-dcb7205e35b3"),
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit,",
                            UserId = "96a4285e-1d56-490a-95c7-2a489bb2e756"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2024, 11, 7, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8157),
                            Grade = 2,
                            ProductId = new Guid("6e81fd57-86d1-48d4-a67b-77deb3ca49fa"),
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit am",
                            UserId = "7a51f572-797a-455c-8d20-2e0baa927672"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2024, 9, 13, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8176),
                            Grade = 2,
                            ProductId = new Guid("2fff7465-e35f-44e1-8949-1ae8e02560f5"),
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt u",
                            UserId = "a53a5ead-388a-45c0-8125-974e1f2c701b"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2024, 11, 13, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8200),
                            Grade = 0,
                            ProductId = new Guid("8b1220a0-4535-40e5-aa31-5baf2489c1b1"),
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipis",
                            UserId = "1d0aa7a3-489e-436d-9ab5-d3c7657ae3bb"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2024, 11, 7, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8223),
                            Grade = 1,
                            ProductId = new Guid("c800e2ec-49d0-48f8-bbb9-b1e90446a3de"),
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, ",
                            UserId = "4c4261ef-00b2-4c14-a0d4-c87b1c48cf42"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2024, 11, 29, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8242),
                            Grade = 2,
                            ProductId = new Guid("c813e839-7bff-49ae-8d6b-6c935725f856"),
                            RatingId = 2,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing e",
                            UserId = "a1fff49c-78e0-4731-8b93-ee0061d42458"
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2024, 10, 21, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8262),
                            Grade = 0,
                            ProductId = new Guid("593cbb12-fa1b-4ce5-b6ce-a0917af5e38a"),
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, co",
                            UserId = "4f7d04ad-48ae-4ded-9ee1-ec5c209ae3b6"
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2024, 10, 23, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8285),
                            Grade = 0,
                            ProductId = new Guid("36fbfacc-2eeb-4d5c-b59c-9a537d6555ce"),
                            RatingId = 3,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed",
                            UserId = "9fc60d83-a6ef-4232-9ee2-33c1a346ce42"
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2024, 9, 5, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8304),
                            Grade = 1,
                            ProductId = new Guid("a1c600e4-8bec-42a5-a99b-19b70021f5fd"),
                            RatingId = 3,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit am",
                            UserId = "071778c3-b4b1-4142-84c6-6e1740a5dc9f"
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2024, 11, 17, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8323),
                            Grade = 5,
                            ProductId = new Guid("fa2bfb7a-16f4-4dce-ac4f-7828e34a967f"),
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, conse",
                            UserId = "ba562c04-22db-4219-ac87-e525c212f21c"
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2024, 10, 15, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8342),
                            Grade = 5,
                            ProductId = new Guid("5bd54185-88ac-42a8-800f-521372c85628"),
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = "c426e9d6-e2c2-410c-8ba6-9a910e1c1bcf"
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2024, 11, 8, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8366),
                            Grade = 0,
                            ProductId = new Guid("511a890d-cb87-4cfc-9006-0a3e2cf66454"),
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = "ad4e5fc8-7c13-4998-becb-1b4a2cdf640b"
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2024, 10, 28, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8408),
                            Grade = 1,
                            ProductId = new Guid("1c2e1586-44ab-4677-baff-3d268d443462"),
                            RatingId = 3,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipi",
                            UserId = "83b3e6c8-8ecd-4828-bef5-a1574bd802d4"
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2024, 10, 19, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8432),
                            Grade = 5,
                            ProductId = new Guid("987416cf-0c31-445b-81f9-65e4c0c750ad"),
                            RatingId = 3,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing eli",
                            UserId = "d008fc18-0b2c-459c-90c3-6b49ce7b3a59"
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2024, 11, 25, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8451),
                            Grade = 2,
                            ProductId = new Guid("9909757d-1273-44ca-b995-43be4202035e"),
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = "5dfd6195-4c58-4df9-b092-418975e27e4b"
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2024, 11, 5, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8470),
                            Grade = 1,
                            ProductId = new Guid("e71199e9-28d1-4a68-8f4a-3fa8f1086587"),
                            RatingId = 3,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = "411ac3c0-d9a8-4f03-9882-271e34272fa8"
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2024, 9, 27, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8489),
                            Grade = 5,
                            ProductId = new Guid("4e70dbf6-d01b-4b6b-8284-4d48e6bda37b"),
                            RatingId = 3,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = "8b1e6299-3a06-4c97-a5fb-ab699a07cac9"
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2024, 10, 24, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8513),
                            Grade = 0,
                            ProductId = new Guid("744c50db-51fa-4372-ae48-7af6a27a0f9f"),
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor ",
                            UserId = "c2786dc9-35a4-4706-ab9f-b1857fb53666"
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2024, 10, 18, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8531),
                            Grade = 2,
                            ProductId = new Guid("aced3166-6aa9-4609-a20d-1237903feeb2"),
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipi",
                            UserId = "19f28431-b557-4d5d-a3ba-eaebc0fbcb0b"
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2024, 11, 1, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8550),
                            Grade = 0,
                            ProductId = new Guid("c1fa525c-4e6a-4392-81ae-78e135cdd626"),
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit,",
                            UserId = "1c1c794f-f753-4e3c-97ff-de7c15915a06"
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2024, 11, 23, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8573),
                            Grade = 2,
                            ProductId = new Guid("d70fcbca-01d4-4a9d-b1da-a0997ba4bc38"),
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt u",
                            UserId = "d359e49c-038b-4e88-a4a8-52f0b482a29b"
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2024, 9, 20, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8593),
                            Grade = 3,
                            ProductId = new Guid("462c8628-ecc6-45b0-a7c4-807d0e48c7fe"),
                            RatingId = 4,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing",
                            UserId = "9fbbabc2-92f0-4891-9815-90fd490d10c4"
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2024, 9, 9, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8612),
                            Grade = 2,
                            ProductId = new Guid("167dacd7-8397-46d1-9f20-dc5b5105cfe6"),
                            RatingId = 4,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adip",
                            UserId = "106300c6-21d5-49fa-8553-a57fbec7657c"
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2024, 11, 11, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8635),
                            Grade = 3,
                            ProductId = new Guid("2de79e70-3efb-46ed-ad60-1038b9062ae1"),
                            RatingId = 5,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed ",
                            UserId = "67e8284e-388f-40af-854a-e30f32df80db"
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2024, 12, 5, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8654),
                            Grade = 2,
                            ProductId = new Guid("74a0af35-a8e2-4724-b7ba-92f3619cc476"),
                            RatingId = 5,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo",
                            UserId = "9428fcb9-6242-4681-82db-5193a1c845dc"
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2024, 11, 11, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8673),
                            Grade = 1,
                            ProductId = new Guid("0230702b-5ed8-49a6-8954-6f88c02fa56f"),
                            RatingId = 6,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = "25df5d26-3ee8-453e-8a71-012cea720b4e"
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2024, 10, 16, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8692),
                            Grade = 4,
                            ProductId = new Guid("af904661-bbca-499a-9f1f-c8067ba5bfda"),
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi",
                            UserId = "425d873a-80b7-4176-91f2-b17fd4539c88"
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2024, 10, 5, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8716),
                            Grade = 5,
                            ProductId = new Guid("e7ea66d0-ba02-4a16-ac15-0efa06f570f0"),
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, c",
                            UserId = "4688b5e0-93aa-4260-84a1-1bd1ac3b9ddb"
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2024, 10, 19, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8735),
                            Grade = 3,
                            ProductId = new Guid("4bdc4182-b784-4239-a0be-f177f21322e8"),
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do",
                            UserId = "f85870ec-1d84-4dff-82fe-fd96de07c437"
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2024, 9, 3, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8753),
                            Grade = 5,
                            ProductId = new Guid("bb8b7564-5817-4413-a74d-6a80e430f05b"),
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed d",
                            UserId = "6ff15237-0d66-4dfa-b7da-b49acf45be24"
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2024, 12, 2, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8773),
                            Grade = 4,
                            ProductId = new Guid("173c7222-b086-4932-b955-2ab68d2e8ed4"),
                            RatingId = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed d",
                            UserId = "cd469971-0140-403d-9e5d-e47b81be2f6c"
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2024, 10, 14, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8796),
                            Grade = 2,
                            ProductId = new Guid("5dfb16df-3b1c-411d-af35-be02d350eb43"),
                            RatingId = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s",
                            UserId = "ef83c56f-83a6-4040-b560-7b3a4ecc4a45"
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2024, 10, 23, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8815),
                            Grade = 3,
                            ProductId = new Guid("ade6af9a-315f-4531-8f9e-49a6250e9b0c"),
                            RatingId = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
                            UserId = "fca49997-df39-473e-b6f1-b92f577684bd"
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2024, 10, 1, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8834),
                            Grade = 2,
                            ProductId = new Guid("c92c2d99-fba7-40ee-bcd7-2f9c6758aa96"),
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididun",
                            UserId = "c0f48eaf-2a75-4b3c-b7b1-21f0b726d005"
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2024, 10, 9, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8853),
                            Grade = 5,
                            ProductId = new Guid("6d94b582-8d1e-4250-bdf3-24ef68be77e0"),
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor i",
                            UserId = "aee4d564-7eb5-40e3-8d9d-b4c87eadeb10"
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2024, 11, 21, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8876),
                            Grade = 4,
                            ProductId = new Guid("51e87650-7cda-4770-98fb-f8deaf502f66"),
                            RatingId = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing el",
                            UserId = "7c7fc9fa-c2dc-492c-8b9c-a35686872a82"
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2024, 9, 11, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8895),
                            Grade = 3,
                            ProductId = new Guid("80073931-6070-44b0-8f48-188eb359146a"),
                            RatingId = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing eli",
                            UserId = "21f187d1-fa27-4c40-b9ce-b3f97978e5ec"
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2024, 10, 23, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8920),
                            Grade = 3,
                            ProductId = new Guid("12cfda6b-c3f8-4ed8-9057-e62dbe5f7ee3"),
                            RatingId = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = "06425404-226b-406c-89f0-10aace2dfdc7"
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2024, 8, 31, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8938),
                            Grade = 2,
                            ProductId = new Guid("a3d1ae5f-6df7-48ee-be47-2dd9bcb8c7fb"),
                            RatingId = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = "a2bb9451-2013-4409-979d-b617fcf8b466"
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2024, 9, 7, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8957),
                            Grade = 3,
                            ProductId = new Guid("8161da29-5345-413c-8f29-4a59dd309483"),
                            RatingId = 8,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisic",
                            UserId = "8a587f49-f071-4bc0-a538-6b9501c989e6"
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2024, 9, 8, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(8980),
                            Grade = 1,
                            ProductId = new Guid("b71f10e6-d1b8-4280-a327-93571c01aa7b"),
                            RatingId = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisic",
                            UserId = "30a7014f-e6f1-430c-a90d-4fdf446b419c"
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2024, 10, 17, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9000),
                            Grade = 0,
                            ProductId = new Guid("7214d8ae-fb2a-4f55-9203-4c108da3caf0"),
                            RatingId = 8,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, ",
                            UserId = "53bdbe8d-015b-48f7-affc-45cfc6f3a507"
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2024, 11, 10, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9019),
                            Grade = 3,
                            ProductId = new Guid("87eb8f90-6825-4e40-809e-5a1b5b70abe4"),
                            RatingId = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, c",
                            UserId = "ceb10535-9af7-43f2-ace1-a0f17e0b2bdf"
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2024, 9, 8, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9095),
                            Grade = 2,
                            ProductId = new Guid("22764704-3a80-4291-8814-4eff46934840"),
                            RatingId = 9,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed",
                            UserId = "3751c8f5-b5b4-42aa-8b6b-2271c18963b6"
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2024, 9, 28, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9118),
                            Grade = 5,
                            ProductId = new Guid("bb9d0073-ea5b-40fa-a109-108ef698342f"),
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = "0e340fba-78d5-4eae-a9da-0c50cbc0f44b"
                        },
                        new
                        {
                            Id = 54,
                            CreationDate = new DateTime(2024, 9, 20, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9137),
                            Grade = 2,
                            ProductId = new Guid("da0b9fcc-4571-49e0-82c0-6c82ce4c0ae3"),
                            RatingId = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit a",
                            UserId = "abb35341-7195-46d6-83cf-82de1d200df4"
                        },
                        new
                        {
                            Id = 55,
                            CreationDate = new DateTime(2024, 9, 13, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9156),
                            Grade = 0,
                            ProductId = new Guid("9127723d-f387-497a-9dd4-ae8cb2e19171"),
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed ",
                            UserId = "eb92cd1a-5276-4fcb-80f4-5bfa985d951a"
                        },
                        new
                        {
                            Id = 56,
                            CreationDate = new DateTime(2024, 10, 6, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9179),
                            Grade = 1,
                            ProductId = new Guid("67ce374c-a619-446d-9676-6a1c77bee0ef"),
                            RatingId = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = "7b7855be-d808-45e0-b9d4-076fd9841ee2"
                        },
                        new
                        {
                            Id = 57,
                            CreationDate = new DateTime(2024, 9, 25, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9198),
                            Grade = 4,
                            ProductId = new Guid("8517b8a9-3d54-4e5c-aba7-f955e241f399"),
                            RatingId = 10,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur",
                            UserId = "b845a5de-7863-41e4-9570-13dbc276bd85"
                        },
                        new
                        {
                            Id = 58,
                            CreationDate = new DateTime(2024, 9, 4, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9217),
                            Grade = 4,
                            ProductId = new Guid("89954212-b525-4ec9-bd0b-515d538fe2c8"),
                            RatingId = 10,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adi",
                            UserId = "53121b7a-b468-4e0e-8b89-560e4c30452a"
                        },
                        new
                        {
                            Id = 59,
                            CreationDate = new DateTime(2024, 9, 11, 22, 45, 25, 814, DateTimeKind.Utc).AddTicks(9236),
                            Grade = 2,
                            ProductId = new Guid("3eb39790-4e7f-4b97-80d5-29617790a904"),
                            RatingId = 10,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor ",
                            UserId = "11d358b6-e907-4637-a68a-6c8dd800f659"
                        });
                });

            modelBuilder.Entity("Reviews.Domain.Models.Review", b =>
                {
                    b.HasOne("Reviews.Domain.Models.Rating", "Rating")
                        .WithMany("Reviews")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Reviews.Domain.Models.Rating", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
